### ISSUE TITLE
Can you provide a simple example

### ISSUE THREAD

**Issue by codeox-he** [adam-drewery/Blazor.WaveSurfer#1]
<code>
import WaveSurfer from 'wavesurfer.js';
window.WaveSurfer = WaveSurfer;
</code>
May I ask if these codes should be written in the<script></script>section of App.razor? I am currently using the ServerSide mode.

**Comment by adam-drewery** [comment]
Hi, sorry its taken a while to respond- I think I need to update my notification settings in here.

To answer your question, I've not really used server-side at all, but this script just needs to be run on the client before using the library. In my case I've put those two lines in a script file which I'm bundling with webpack, but just a <script> element in your root page should work too.

Hope that helps! If you discover there are some other steps involved in making this work for server-side Blazor or if it should be changed in some way I'd be happy to update it, just let me know.
